server:
  port: 8000

spring:
  config:
    activate:
      on-profile: dev
  
  # datasource는 spring 아래에 있어야 함!
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inspire
    username: root
    password: 1004

  jpa:
    hibernate:
    #create, create-drop, update, none
      ddl-auto: none

    #콘솔 출력
    show-sql: true
    properties:
      hibernate:
      
      #mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true


    # redis -  in memory DB
    # docker
    #docker run -d --name redis-container -p 6379:6379 redis:7.2
    #docker exec -it redis-container redis-cli
    #docker run -d --name redis-insight -p 8001:8001 redis/redisinsight:latest
    #http://localhost:8001
    data:
      redis:
        host: localhost
        port: 6379
        password:
        database: 6000ms


jwt:
  # 개발용 시크릿 키 (운영에서는 환경 변수 등으로 외부 주입)
  secret: ${JWT_SECRET_KEY}
  
